export default function Home() {
  return (
    <></>
    // <Head>
    //   <title>중고마켓</title>
    //   <meta name="description" content="Generated by create next app" />
    //   <link rel="icon" href="/favicon.ico" />
    // </Head>
  )
}
