name: Deploy Joonggomarket App(S3, EC2)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 20.15.0 설치 및 yarn 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.0'

      - name: Install yarn
        run: npm install -g yarn

      ## 3. 의존성 설치
      - name: Install dependencies
        run: yarn install

      # 4. 정적 사이트 빌드
      - name: Build static files
        run: yarn build:ssg

      # 5. S3 업로드
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './out'

      # 6. SSH 키 복원 및 권한 설정
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh # SSH 디렉토리 생성
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 7. 동적 사이트 빌드
      - name: Build dynamic files
        run: yarn build

      # 8. EC2 서버 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ~/.ssh/id_rsa
          port: 22
          script: |
            cd /home/ec2-user/joonggomarket_front
            rm -rf *
            PORT=3000
            PID=$(lsof -t -i:$PORT)
            if [ -n "$PID" ]; then
              echo "Stopping process on port $PORT (PID: $PID)..."
              kill -9 $PID
            else
              echo "No process found on port $PORT."
            fi
            yarn install
            yarn start > /dev/null 2>&1 &
