name: Deploy Joonggomarket App(S3, EC2)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 20.15.0 설치 및 yarn 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.0'

      - name: Install yarn
        run: npm install -g yarn

      # 3. 의존성 설치
      - name: Install dependencies
        run: yarn install

      # 6. 동적 사이트 빌드
      - name: Build dynamic files
        run: |
          echo "Saving SSH key to a file..."
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

          echo "Building dynamic files..."
          yarn build

          echo "Current directory file list:"
          pwd
          ls -al

          echo "Cleaning EC2 target directory and stopping port 3000 process..."
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            TARGET_DIR="/home/ec2-user/joonggomarket_front"
            PORT=3000

            echo "Stopping any process running on port $PORT..."
            PID=$(lsof -t -i:$PORT)
            if [ -n "$PID" ]; then
              echo "Stopping process with PID $PID..."
              kill -9 $PID
            else
              echo "No process found on port $PORT."
            fi

            echo "Clearing target directory: $TARGET_DIR"
            rm -rf $TARGET_DIR/*
          EOF

          echo "Uploading files to EC2..."
          scp -o StrictHostKeyChecking=no -i ec2_key.pem \
            -r ./.next ./node_modules ./yarn.lock ./package.json \
            ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/joonggomarket_front/

          echo "Deployment completed."

      # 7. EC2 서버 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            yarn install
            yarn start > /dev/null 2>&1 &

      # 4. 정적 사이트 빌드
      - name: Build static files
        run: yarn build:ssg

      # 5. S3 업로드
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './out'
